"""OpenDistillation v0 prototype helpers.

The default path intentionally starts with deterministic local helpers only.
Optional model training and comparison helpers stay lazy-loaded.
"""

from .dataset import DatasetValidationError, rows_to_jsonl, validate_dataset, validate_dataset_row
from .engines import ExportEngine, ExportRequest, ExportResult, TrainingEngine, TrainingRequest, TrainingResult
from .evaluation import SAMPLE_FACT_COMPARISON_ROWS, build_sample_fact_comparison_rows
from .fact_ledger import (
    DEFAULT_FACT_TRAIN_EXAMPLES_PER_FACT,
    FactAnswerScore,
    FactCard,
    FactOutputScore,
    FactQualityGateReport,
    FactQualityIssue,
    FactReadinessReport,
    FactScoreComparison,
    FactScoreComparisonItem,
    FactTrainEvalSplit,
    analyze_fact_quality_gate,
    analyze_fact_readiness,
    build_fact_comparison_rows,
    build_fact_train_eval_split,
    compare_fact_scores,
    extract_fact_ledger,
    format_fact_quality_report,
    format_fact_readiness_report,
    format_fact_score_report,
    score_fact_answer,
    score_fact_outputs,
)
from .teacher import (
    DEFAULT_REAL_TEACHER_MODEL,
    HuggingFaceLocalTeacherEngine,
    MockTeacherEngine,
    RealTeacherConfig,
    RealTeacherDependencyError,
    RealTeacherError,
    RealTeacherGenerationError,
    RealTeacherModelLoadError,
    RealTeacherOutputError,
    TeacherEngine,
    TeacherRequest,
    build_teacher_prompt,
    explain_teacher_failure,
    generate_mock_qa_pairs,
    parse_teacher_jsonl_output,
)
from .text import LoadedTextDocument, TextChunk, TextValidationError, chunk_text, load_text_document
from .quality import (
    DatasetQualityIssue,
    DatasetQualityReport,
    analyze_dataset_quality,
    format_dataset_quality_report,
)
from .comparison import (
    BeforeAfterComparisonEngine,
    BeforeAfterComparisonItem,
    BeforeAfterComparisonRequest,
    BeforeAfterComparisonResult,
    ComparisonConfigurationError,
    ComparisonDependencyError,
    ComparisonExample,
    build_comparison_request,
)
from .runtime import (
    OPTIONAL_COMPARISON_PACKAGES,
    OPTIONAL_TRAINING_INSTALL_PACKAGES,
    OPTIONAL_TRAINING_PACKAGES,
    RuntimeCheck,
    build_pip_install_command,
    check_training_runtime,
    explain_runtime_failure,
    format_runtime_check,
)
from .training import (
    DEFAULT_STUDENT_MODEL,
    SFTLoRAConfig,
    SFTLoRATrainingEngine,
    SFTPreviewRow,
    TrainingConfigurationError,
    TrainingDependencyError,
    build_sft_preview_rows,
    build_training_request,
    format_sft_preview_report,
    format_sft_rows,
)

__all__ = [
    "DatasetValidationError",
    "DatasetQualityIssue",
    "DatasetQualityReport",
    "DEFAULT_FACT_TRAIN_EXAMPLES_PER_FACT",
    "DEFAULT_STUDENT_MODEL",
    "DEFAULT_REAL_TEACHER_MODEL",
    "BeforeAfterComparisonEngine",
    "BeforeAfterComparisonItem",
    "BeforeAfterComparisonRequest",
    "BeforeAfterComparisonResult",
    "ComparisonConfigurationError",
    "ComparisonDependencyError",
    "ComparisonExample",
    "OPTIONAL_COMPARISON_PACKAGES",
    "OPTIONAL_TRAINING_INSTALL_PACKAGES",
    "OPTIONAL_TRAINING_PACKAGES",
    "ExportEngine",
    "ExportRequest",
    "ExportResult",
    "HuggingFaceLocalTeacherEngine",
    "LoadedTextDocument",
    "MockTeacherEngine",
    "RealTeacherConfig",
    "RealTeacherDependencyError",
    "RealTeacherError",
    "RealTeacherGenerationError",
    "RealTeacherModelLoadError",
    "RealTeacherOutputError",
    "TextChunk",
    "TextValidationError",
    "RuntimeCheck",
    "TeacherEngine",
    "TeacherRequest",
    "TrainingEngine",
    "TrainingRequest",
    "TrainingResult",
    "SFTLoRAConfig",
    "SFTLoRATrainingEngine",
    "SFTPreviewRow",
    "SAMPLE_FACT_COMPARISON_ROWS",
    "FactAnswerScore",
    "FactCard",
    "FactOutputScore",
    "FactQualityGateReport",
    "FactQualityIssue",
    "FactReadinessReport",
    "FactScoreComparison",
    "FactScoreComparisonItem",
    "FactTrainEvalSplit",
    "TrainingConfigurationError",
    "TrainingDependencyError",
    "analyze_fact_quality_gate",
    "analyze_fact_readiness",
    "build_comparison_request",
    "build_fact_comparison_rows",
    "build_fact_train_eval_split",
    "build_sample_fact_comparison_rows",
    "build_pip_install_command",
    "build_sft_preview_rows",
    "build_teacher_prompt",
    "build_training_request",
    "check_training_runtime",
    "chunk_text",
    "compare_fact_scores",
    "analyze_dataset_quality",
    "extract_fact_ledger",
    "explain_teacher_failure",
    "explain_runtime_failure",
    "format_sft_rows",
    "format_sft_preview_report",
    "format_dataset_quality_report",
    "format_fact_quality_report",
    "format_fact_readiness_report",
    "format_fact_score_report",
    "format_runtime_check",
    "generate_mock_qa_pairs",
    "load_text_document",
    "parse_teacher_jsonl_output",
    "rows_to_jsonl",
    "score_fact_answer",
    "score_fact_outputs",
    "validate_dataset",
    "validate_dataset_row",
]
